name: 🚀 Deploy Next.js to VPS

on:
  push:
    branches:
      - main
      - stag

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🔐 Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: 🚀 Deploy to VPS
        run: |
          ssh -T -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF

          export PATH=/www/server/nodejs/v22.17.1/bin:$PATH

          if [ "${GITHUB_REF##*/}" = "main" ]; then
            APP_DIR="/www/wwwroot/theclevar"
            PM2_NAME="clevar"
            PORT=3000
            BRANCH="main"
          else
            APP_DIR="/www/wwwroot/theclevarstag"
            PM2_NAME="clevarstag"
            PORT=3001
            BRANCH="stag"
          fi

          echo "🚀 Deploying branch: $BRANCH"
          echo "📁 Directory: $APP_DIR"

          # If folder doesn't exist → clone
          if [ ! -d "$APP_DIR" ]; then
            git clone -b $BRANCH https://github.com/himanshu05626/theclevar.git $APP_DIR
          fi

          cd $APP_DIR

          # Pull latest
          git fetch origin
          git reset --hard origin/$BRANCH

          # Install clean deps
          npm ci

          # Prisma
          npx prisma generate

          # Build
          npm run build

          # Start or reload PM2
          pm2 describe $PM2_NAME > /dev/null
          if [ $? -eq 0 ]; then
            echo "🔄 Reloading $PM2_NAME"
            pm2 reload $PM2_NAME --update-env
          else
            echo "🆕 Starting $PM2_NAME"
            PORT=$PORT pm2 start npm --name "$PM2_NAME" -- start
          fi

          pm2 save

          echo "✅ Deployment Complete"

          EOF